export default {
  // FONT
  FONT_SIZE_EXTRA_SMALL: 12,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_NORMAL: 16,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_EXTRA_LARGE: 22,

  //ICON SIZE
  ICON_SIZE_SMALL: 20,
  ICON_SIZE_MEDIUM: 30,
  ICON_SIZE_LARGE: 40,

  // FONT FAMILY
  FONG_FAMILY: null,

  // COLORS
  PRIMARY_COLOR: '#F62459',
  LIGHT_PRIMARY_COLOR: '#03F7EB90',
  RED_BACKGROUND_COLOR: '#AB2346',
  WHITE_COLOR: '#FFFFFF',
  SECONDARY_WHITE_COLOR: '#E4E6EB',
  LIGHT_BACKGROUND_COLOR: '#C9DAEA',
  BLACK_COLOR: '#191516',
  DARK_COLOR: '#3F3D56',
  BORDER_LINE_COLOR: '#8B8B8B',
  RED_ERROR_COLOR: '#eb4345',
  IMAGE_WATERMARK: '#ab2346',

  TEXT_COLOR: '#464353',

  WON_COLOR: '#00B295',
  LOST_COLOR: '#AB2346',

  TEXT_SECONDARY_COLOR: '#9DA3AB',
  BORDER_RADIUS_COLOR: '#E9E9E9',

  PROGRESS_BACKGROUND_COLOR: '#3d5875',
  PROGRESS_BACKGROUND_RED_COLOR: '#DF1818',
  // WEIGHT
  FONT_WEIGHT_LIGHT: '500',
  FONT_WEIGHT_MEDIUM: '700',
  FONT_WEIGHT_HEAVY: 'bold',

  // BORDER RADIUS
  IMAGE_BORDER_RADIUS: 5,
  BUTTON_BORDER_RADIUS: 5,
  PROFILE_IMAGE_BORDER_RADIUS: 99,
};
